### ISSUE TITLE
Create call node crashes when using JSONata at Call Hook/Status URL 

### ISSUE THREAD

**Issue by 78wesley** [jambonz/node-red-contrib-jambonz#87]
Hi,

I found a problem with the create-call node. When I use JSONata at the Call Hook URL or Call Status URL and save the node config. after that when I click on deploy my Node-RED/FlowFuse instance crash.
The error I got is this:

```
8/14/2024 12:41:15 PM  [error]   Error: Calls to RED.util.evaluateJSONataExpression must include a callback.
    at evaluateJSONataExpression (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:780:23)
    at Object.evaluateNodeProperty (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:681:18)
    at exports.new_resolve (/data/node_modules/@jambonz/node-red-contrib-jambonz/src/nodes/libs.js:59:25)
    at create_call._inputCallback (/data/node_modules/@jambonz/node-red-contrib-jambonz/src/nodes/create_call.js:52:19)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:214:26
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:206:11)
    at Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:190:25)
    at Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:499:10)
    at deliverMessageToDestination (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:803:40)
    ```

**Comment by avoylenko** [comment]
@78wesley fixed in version 2.4.25
